---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: ''
sections:
- type: directory
  path: content/oyun
  label: Oyun
  create: all
  match: "**/*"
  templates:
  - oyun
- type: directory
  path: content/video
  label: Video
  create: all
  match: "**/*"
  templates:
  - video
- type: directory
  path: content/anime
  label: Anime
  create: all
  match: "**/*"
  templates:
  - anime
- type: directory
  path: content/yazi
  label: Yazı
  create: all
  match: "**/*"
  templates:
  - yazi
- type: directory
  path: content/sayfa
  label: Sayfa
  create: all
  match: "**/*"
  templates:
  - sayfa
upload_dir: website/assets
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=development
  - HUGO_VERSION=0.74.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server --ignoreCache --disableFastRender -D -E -F
    --renderToDisk -d public
version: 0.74.3
