---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: ''
sections:
- type: heading
  label: Çeviriler
- type: directory
  path: content/oyun
  label: Oyunlar
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - oyun
- type: directory
  path: content/video
  label: Videolar
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - video_youtube
  - video_mp4
  - video_iframe
- type: directory
  path: content/anime
  label: Animeler
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - anime_thumbnail
  - anime_mp4
  - anime_iframe
- type: heading
  label: Diğer İçerikler
- type: directory
  path: content/yazi
  label: Yazılar
  create: documents
  match: "**/*"
  exclude: _index*
  new_doc_ext: md
  templates:
  - yazi
- type: directory
  path: content/sayfa
  label: Sayfalar
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - sayfa
- type: directory
  path: content/indir
  label: İndirme Linkleri
  create: documents
  match: "**/*"
  exclude: _index*
  templates:
  - indir
upload_dir: website/assets
public_path: https://res.cloudinary.com/bluesoulceviriekibi/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=development
  - HUGO_VERSION=0.92.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server --gc --ignoreCache --disableFastRender -D -e
    development -w --renderToDisk -d public --cleanDestinationDir
version: 0.92.0
