# This is a basic workflow to help you get started with Actions

name: Build Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, delete, create]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - uses: wei/git-sync@master
      with:
        source_repo: "https://bluesoulceviriekibi:279da1bb89382fbf86d241bc7122c1d6d91c6c24github.com/bluesoulceviriekibi/website.git"
        source_branch: "refs/remotes/source/*"
        destination_repo: "https://bluesoulceviriekibi:279da1bb89382fbf86d241bc7122c1d6d91c6c24github.com/bluesoulceviriekibiuser/bsce-website.git"
        destination_branch: "refs/heads/*"

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line scripts
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
